---
output: html_document
author: Hennie Engebretsen
  chunk_output_type: console
---

Assigment 1

```{r}
#| message: false
#| warning: false
#| code-fold: true

library(tidyverse)

set.seed(1)
population <- rnorm(1000000, mean = 1.5, sd = 3)


samp1 <- data.frame(y = sample(population, 8, replace = FALSE))

samp2 <- data.frame(y = sample(population, 40, replace = FALSE))


m1 <- lm(y ~ 1, data = samp1)
m2 <- lm(y ~ 1, data = samp2)

summary(m1)

mean(samp1$y)
coef(m1)
sd(samp1$y)
sd(samp1$y) /sqrt(8)

```

### Oppgave 1

Ved bruk av regresjonsmodellene lm1 og lm2 skal begrepene estimat, SE (standard error) t-verdi og p-verdi forklares. I regresjonsmodellene lm1 og lm2 det kun den konstante variablen som blir estimert da det ikke er noen uavhengig variabel. Dette vil si at det kun er gjennomsnittet til den konstante variablen som blir estimert, det vil si at den estimerte verdiene til de ulike regresjonsmodellene er gjennomsnittet av det aktuelle utvalget for y i de ulike modellene dette tilsvarer for m1 1.0677

SE(standard error) er standardfeilen vil være et mål på hvordan et statisitsk estimat til et utvalg kan variere fra populasjonen. For modellen m1 er standard error 1.25 dette viser at det er noe usikkerhet knyttet til et estimat av gjennomsnittet.

T-verdi kan ses på som en statisitksk verdi hvor langt gjennomsnittet er fra befolkningen. Jo høyere t-verdien er kan

p-verdien sier noe om usikkerheten i trekningen av utvalget

### Oppgave 2

De to ulike modellene får ulike resultater en av grunnene til dette er at det er ulikt utvalg i de to ulike modellene i lm1 er det n =8, mens i lm2 er det n =40. Utvalgsstørrelsen vil ha en innvirkning på resultatene, ved at man har et større utvalg vil den statistiske styrken være høyere og det vil dermed være lettere å kunne oppdage om det vil være en reell effekt en ser. Det samme vil gjelde for standardfeil ved et større utvalg vil standardfeil til gjennomsnittet reduseres, en vil da ha mindre konfidensintervall og estimatene vil kunne bli mer presist. 


## Oppgave 3

De mørke skyggeområdene

